// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Modulith.Modules.Users.Infrastructures.Data.CompiledModels
{
    public partial class UserDbContextModel
    {
        partial void Initialize()
        {
            var identityRole = IdentityRoleEntityType.Create(this);
            var identityRoleClaim = IdentityRoleClaimEntityType.Create(this);
            var identityUserClaim = IdentityUserClaimEntityType.Create(this);
            var identityUserLogin = IdentityUserLoginEntityType.Create(this);
            var identityUserRole = IdentityUserRoleEntityType.Create(this);
            var identityUserToken = IdentityUserTokenEntityType.Create(this);
            var address = AddressEntityType.Create(this);
            var applicationUser = ApplicationUserEntityType.Create(this);

            IdentityRoleClaimEntityType.CreateForeignKey1(identityRoleClaim, identityRole);
            IdentityUserClaimEntityType.CreateForeignKey1(identityUserClaim, applicationUser);
            IdentityUserLoginEntityType.CreateForeignKey1(identityUserLogin, applicationUser);
            IdentityUserRoleEntityType.CreateForeignKey1(identityUserRole, identityRole);
            IdentityUserRoleEntityType.CreateForeignKey2(identityUserRole, applicationUser);
            IdentityUserTokenEntityType.CreateForeignKey1(identityUserToken, applicationUser);
            AddressEntityType.CreateForeignKey1(address, applicationUser);

            IdentityRoleEntityType.CreateAnnotations(identityRole);
            IdentityRoleClaimEntityType.CreateAnnotations(identityRoleClaim);
            IdentityUserClaimEntityType.CreateAnnotations(identityUserClaim);
            IdentityUserLoginEntityType.CreateAnnotations(identityUserLogin);
            IdentityUserRoleEntityType.CreateAnnotations(identityUserRole);
            IdentityUserTokenEntityType.CreateAnnotations(identityUserToken);
            AddressEntityType.CreateAnnotations(address);
            ApplicationUserEntityType.CreateAnnotations(applicationUser);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "8.0.4");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
            AddRuntimeAnnotation("Relational:RelationalModel", CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var identityRole = FindEntityType("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            identityRole.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var microsoftAspNetCoreIdentityIdentityRoleSystemGuidTableBase = new TableBase("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null, relationalModel);
            var concurrency_stampColumnBase = new ColumnBase<ColumnMappingBase>("concurrency_stamp", "text", microsoftAspNetCoreIdentityIdentityRoleSystemGuidTableBase)
            {
                IsNullable = true
            };
            microsoftAspNetCoreIdentityIdentityRoleSystemGuidTableBase.Columns.Add("concurrency_stamp", concurrency_stampColumnBase);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("id", "uuid", microsoftAspNetCoreIdentityIdentityRoleSystemGuidTableBase);
            microsoftAspNetCoreIdentityIdentityRoleSystemGuidTableBase.Columns.Add("id", idColumnBase);
            var nameColumnBase = new ColumnBase<ColumnMappingBase>("name", "character varying(256)", microsoftAspNetCoreIdentityIdentityRoleSystemGuidTableBase)
            {
                IsNullable = true
            };
            microsoftAspNetCoreIdentityIdentityRoleSystemGuidTableBase.Columns.Add("name", nameColumnBase);
            var normalized_nameColumnBase = new ColumnBase<ColumnMappingBase>("normalized_name", "character varying(256)", microsoftAspNetCoreIdentityIdentityRoleSystemGuidTableBase)
            {
                IsNullable = true
            };
            microsoftAspNetCoreIdentityIdentityRoleSystemGuidTableBase.Columns.Add("normalized_name", normalized_nameColumnBase);
            relationalModel.DefaultTables.Add("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", microsoftAspNetCoreIdentityIdentityRoleSystemGuidTableBase);
            var microsoftAspNetCoreIdentityIdentityRoleSystemGuidMappingBase = new TableMappingBase<ColumnMappingBase>(identityRole, microsoftAspNetCoreIdentityIdentityRoleSystemGuidTableBase, true);
            microsoftAspNetCoreIdentityIdentityRoleSystemGuidTableBase.AddTypeMapping(microsoftAspNetCoreIdentityIdentityRoleSystemGuidMappingBase, false);
            defaultTableMappings.Add(microsoftAspNetCoreIdentityIdentityRoleSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, identityRole.FindProperty("Id")!, microsoftAspNetCoreIdentityIdentityRoleSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)concurrency_stampColumnBase, identityRole.FindProperty("ConcurrencyStamp")!, microsoftAspNetCoreIdentityIdentityRoleSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase, identityRole.FindProperty("Name")!, microsoftAspNetCoreIdentityIdentityRoleSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)normalized_nameColumnBase, identityRole.FindProperty("NormalizedName")!, microsoftAspNetCoreIdentityIdentityRoleSystemGuidMappingBase);

            var tableMappings = new List<TableMapping>();
            identityRole.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var aspNetRolesTable = new Table("AspNetRoles", null, relationalModel);
            var idColumn = new Column("id", "uuid", aspNetRolesTable);
            aspNetRolesTable.Columns.Add("id", idColumn);
            var concurrency_stampColumn = new Column("concurrency_stamp", "text", aspNetRolesTable)
            {
                IsNullable = true
            };
            aspNetRolesTable.Columns.Add("concurrency_stamp", concurrency_stampColumn);
            var nameColumn = new Column("name", "character varying(256)", aspNetRolesTable)
            {
                IsNullable = true
            };
            aspNetRolesTable.Columns.Add("name", nameColumn);
            var normalized_nameColumn = new Column("normalized_name", "character varying(256)", aspNetRolesTable)
            {
                IsNullable = true
            };
            aspNetRolesTable.Columns.Add("normalized_name", normalized_nameColumn);
            var pk_asp_net_roles = new UniqueConstraint("pk_asp_net_roles", aspNetRolesTable, new[] { idColumn });
            aspNetRolesTable.PrimaryKey = pk_asp_net_roles;
            var pk_asp_net_rolesUc = RelationalModel.GetKey(this,
                "Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>",
                new[] { "Id" });
            pk_asp_net_roles.MappedKeys.Add(pk_asp_net_rolesUc);
            RelationalModel.GetOrCreateUniqueConstraints(pk_asp_net_rolesUc).Add(pk_asp_net_roles);
            aspNetRolesTable.UniqueConstraints.Add("pk_asp_net_roles", pk_asp_net_roles);
            var roleNameIndex = new TableIndex(
            "RoleNameIndex", aspNetRolesTable, new[] { normalized_nameColumn }, true);
            var roleNameIndexIx = RelationalModel.GetIndex(this,
                "Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>",
                new[] { "NormalizedName" });
            roleNameIndex.MappedIndexes.Add(roleNameIndexIx);
            RelationalModel.GetOrCreateTableIndexes(roleNameIndexIx).Add(roleNameIndex);
            aspNetRolesTable.Indexes.Add("RoleNameIndex", roleNameIndex);
            relationalModel.Tables.Add(("AspNetRoles", null), aspNetRolesTable);
            var aspNetRolesTableMapping = new TableMapping(identityRole, aspNetRolesTable, true);
            aspNetRolesTable.AddTypeMapping(aspNetRolesTableMapping, false);
            tableMappings.Add(aspNetRolesTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, identityRole.FindProperty("Id")!, aspNetRolesTableMapping);
            RelationalModel.CreateColumnMapping(concurrency_stampColumn, identityRole.FindProperty("ConcurrencyStamp")!, aspNetRolesTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn, identityRole.FindProperty("Name")!, aspNetRolesTableMapping);
            RelationalModel.CreateColumnMapping(normalized_nameColumn, identityRole.FindProperty("NormalizedName")!, aspNetRolesTableMapping);

            var identityRoleClaim = FindEntityType("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>")!;

            var defaultTableMappings0 = new List<TableMappingBase<ColumnMappingBase>>();
            identityRoleClaim.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings0);
            var microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidTableBase = new TableBase("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", null, relationalModel);
            var claim_typeColumnBase = new ColumnBase<ColumnMappingBase>("claim_type", "text", microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidTableBase)
            {
                IsNullable = true
            };
            microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidTableBase.Columns.Add("claim_type", claim_typeColumnBase);
            var claim_valueColumnBase = new ColumnBase<ColumnMappingBase>("claim_value", "text", microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidTableBase)
            {
                IsNullable = true
            };
            microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidTableBase.Columns.Add("claim_value", claim_valueColumnBase);
            var idColumnBase0 = new ColumnBase<ColumnMappingBase>("id", "integer", microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidTableBase);
            microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidTableBase.Columns.Add("id", idColumnBase0);
            var role_idColumnBase = new ColumnBase<ColumnMappingBase>("role_id", "uuid", microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidTableBase);
            microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidTableBase.Columns.Add("role_id", role_idColumnBase);
            relationalModel.DefaultTables.Add("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidTableBase);
            var microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidMappingBase = new TableMappingBase<ColumnMappingBase>(identityRoleClaim, microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidTableBase, true);
            microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidTableBase.AddTypeMapping(microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidMappingBase, false);
            defaultTableMappings0.Add(microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase0, identityRoleClaim.FindProperty("Id")!, microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)claim_typeColumnBase, identityRoleClaim.FindProperty("ClaimType")!, microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)claim_valueColumnBase, identityRoleClaim.FindProperty("ClaimValue")!, microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)role_idColumnBase, identityRoleClaim.FindProperty("RoleId")!, microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidMappingBase);

            var tableMappings0 = new List<TableMapping>();
            identityRoleClaim.SetRuntimeAnnotation("Relational:TableMappings", tableMappings0);
            var aspNetRoleClaimsTable = new Table("AspNetRoleClaims", null, relationalModel);
            var idColumn0 = new Column("id", "integer", aspNetRoleClaimsTable);
            aspNetRoleClaimsTable.Columns.Add("id", idColumn0);
            idColumn0.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            var claim_typeColumn = new Column("claim_type", "text", aspNetRoleClaimsTable)
            {
                IsNullable = true
            };
            aspNetRoleClaimsTable.Columns.Add("claim_type", claim_typeColumn);
            var claim_valueColumn = new Column("claim_value", "text", aspNetRoleClaimsTable)
            {
                IsNullable = true
            };
            aspNetRoleClaimsTable.Columns.Add("claim_value", claim_valueColumn);
            var role_idColumn = new Column("role_id", "uuid", aspNetRoleClaimsTable);
            aspNetRoleClaimsTable.Columns.Add("role_id", role_idColumn);
            var pk_asp_net_role_claims = new UniqueConstraint("pk_asp_net_role_claims", aspNetRoleClaimsTable, new[] { idColumn0 });
            aspNetRoleClaimsTable.PrimaryKey = pk_asp_net_role_claims;
            var pk_asp_net_role_claimsUc = RelationalModel.GetKey(this,
                "Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>",
                new[] { "Id" });
            pk_asp_net_role_claims.MappedKeys.Add(pk_asp_net_role_claimsUc);
            RelationalModel.GetOrCreateUniqueConstraints(pk_asp_net_role_claimsUc).Add(pk_asp_net_role_claims);
            aspNetRoleClaimsTable.UniqueConstraints.Add("pk_asp_net_role_claims", pk_asp_net_role_claims);
            var ix_asp_net_role_claims_role_id = new TableIndex(
            "ix_asp_net_role_claims_role_id", aspNetRoleClaimsTable, new[] { role_idColumn }, false);
            var ix_asp_net_role_claims_role_idIx = RelationalModel.GetIndex(this,
                "Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>",
                new[] { "RoleId" });
            ix_asp_net_role_claims_role_id.MappedIndexes.Add(ix_asp_net_role_claims_role_idIx);
            RelationalModel.GetOrCreateTableIndexes(ix_asp_net_role_claims_role_idIx).Add(ix_asp_net_role_claims_role_id);
            aspNetRoleClaimsTable.Indexes.Add("ix_asp_net_role_claims_role_id", ix_asp_net_role_claims_role_id);
            relationalModel.Tables.Add(("AspNetRoleClaims", null), aspNetRoleClaimsTable);
            var aspNetRoleClaimsTableMapping = new TableMapping(identityRoleClaim, aspNetRoleClaimsTable, true);
            aspNetRoleClaimsTable.AddTypeMapping(aspNetRoleClaimsTableMapping, false);
            tableMappings0.Add(aspNetRoleClaimsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn0, identityRoleClaim.FindProperty("Id")!, aspNetRoleClaimsTableMapping);
            RelationalModel.CreateColumnMapping(claim_typeColumn, identityRoleClaim.FindProperty("ClaimType")!, aspNetRoleClaimsTableMapping);
            RelationalModel.CreateColumnMapping(claim_valueColumn, identityRoleClaim.FindProperty("ClaimValue")!, aspNetRoleClaimsTableMapping);
            RelationalModel.CreateColumnMapping(role_idColumn, identityRoleClaim.FindProperty("RoleId")!, aspNetRoleClaimsTableMapping);

            var identityUserClaim = FindEntityType("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>")!;

            var defaultTableMappings1 = new List<TableMappingBase<ColumnMappingBase>>();
            identityUserClaim.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings1);
            var microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidTableBase = new TableBase("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", null, relationalModel);
            var claim_typeColumnBase0 = new ColumnBase<ColumnMappingBase>("claim_type", "text", microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidTableBase)
            {
                IsNullable = true
            };
            microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidTableBase.Columns.Add("claim_type", claim_typeColumnBase0);
            var claim_valueColumnBase0 = new ColumnBase<ColumnMappingBase>("claim_value", "text", microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidTableBase)
            {
                IsNullable = true
            };
            microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidTableBase.Columns.Add("claim_value", claim_valueColumnBase0);
            var idColumnBase1 = new ColumnBase<ColumnMappingBase>("id", "integer", microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidTableBase);
            microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidTableBase.Columns.Add("id", idColumnBase1);
            var user_idColumnBase = new ColumnBase<ColumnMappingBase>("user_id", "uuid", microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidTableBase);
            microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidTableBase.Columns.Add("user_id", user_idColumnBase);
            relationalModel.DefaultTables.Add("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidTableBase);
            var microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidMappingBase = new TableMappingBase<ColumnMappingBase>(identityUserClaim, microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidTableBase, true);
            microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidTableBase.AddTypeMapping(microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidMappingBase, false);
            defaultTableMappings1.Add(microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase1, identityUserClaim.FindProperty("Id")!, microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)claim_typeColumnBase0, identityUserClaim.FindProperty("ClaimType")!, microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)claim_valueColumnBase0, identityUserClaim.FindProperty("ClaimValue")!, microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)user_idColumnBase, identityUserClaim.FindProperty("UserId")!, microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidMappingBase);

            var tableMappings1 = new List<TableMapping>();
            identityUserClaim.SetRuntimeAnnotation("Relational:TableMappings", tableMappings1);
            var aspNetUserClaimsTable = new Table("AspNetUserClaims", null, relationalModel);
            var idColumn1 = new Column("id", "integer", aspNetUserClaimsTable);
            aspNetUserClaimsTable.Columns.Add("id", idColumn1);
            idColumn1.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            var claim_typeColumn0 = new Column("claim_type", "text", aspNetUserClaimsTable)
            {
                IsNullable = true
            };
            aspNetUserClaimsTable.Columns.Add("claim_type", claim_typeColumn0);
            var claim_valueColumn0 = new Column("claim_value", "text", aspNetUserClaimsTable)
            {
                IsNullable = true
            };
            aspNetUserClaimsTable.Columns.Add("claim_value", claim_valueColumn0);
            var user_idColumn = new Column("user_id", "uuid", aspNetUserClaimsTable);
            aspNetUserClaimsTable.Columns.Add("user_id", user_idColumn);
            var pk_asp_net_user_claims = new UniqueConstraint("pk_asp_net_user_claims", aspNetUserClaimsTable, new[] { idColumn1 });
            aspNetUserClaimsTable.PrimaryKey = pk_asp_net_user_claims;
            var pk_asp_net_user_claimsUc = RelationalModel.GetKey(this,
                "Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>",
                new[] { "Id" });
            pk_asp_net_user_claims.MappedKeys.Add(pk_asp_net_user_claimsUc);
            RelationalModel.GetOrCreateUniqueConstraints(pk_asp_net_user_claimsUc).Add(pk_asp_net_user_claims);
            aspNetUserClaimsTable.UniqueConstraints.Add("pk_asp_net_user_claims", pk_asp_net_user_claims);
            var ix_asp_net_user_claims_user_id = new TableIndex(
            "ix_asp_net_user_claims_user_id", aspNetUserClaimsTable, new[] { user_idColumn }, false);
            var ix_asp_net_user_claims_user_idIx = RelationalModel.GetIndex(this,
                "Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>",
                new[] { "UserId" });
            ix_asp_net_user_claims_user_id.MappedIndexes.Add(ix_asp_net_user_claims_user_idIx);
            RelationalModel.GetOrCreateTableIndexes(ix_asp_net_user_claims_user_idIx).Add(ix_asp_net_user_claims_user_id);
            aspNetUserClaimsTable.Indexes.Add("ix_asp_net_user_claims_user_id", ix_asp_net_user_claims_user_id);
            relationalModel.Tables.Add(("AspNetUserClaims", null), aspNetUserClaimsTable);
            var aspNetUserClaimsTableMapping = new TableMapping(identityUserClaim, aspNetUserClaimsTable, true);
            aspNetUserClaimsTable.AddTypeMapping(aspNetUserClaimsTableMapping, false);
            tableMappings1.Add(aspNetUserClaimsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn1, identityUserClaim.FindProperty("Id")!, aspNetUserClaimsTableMapping);
            RelationalModel.CreateColumnMapping(claim_typeColumn0, identityUserClaim.FindProperty("ClaimType")!, aspNetUserClaimsTableMapping);
            RelationalModel.CreateColumnMapping(claim_valueColumn0, identityUserClaim.FindProperty("ClaimValue")!, aspNetUserClaimsTableMapping);
            RelationalModel.CreateColumnMapping(user_idColumn, identityUserClaim.FindProperty("UserId")!, aspNetUserClaimsTableMapping);

            var identityUserLogin = FindEntityType("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>")!;

            var defaultTableMappings2 = new List<TableMappingBase<ColumnMappingBase>>();
            identityUserLogin.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings2);
            var microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidTableBase = new TableBase("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", null, relationalModel);
            var login_providerColumnBase = new ColumnBase<ColumnMappingBase>("login_provider", "text", microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidTableBase);
            microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidTableBase.Columns.Add("login_provider", login_providerColumnBase);
            var provider_display_nameColumnBase = new ColumnBase<ColumnMappingBase>("provider_display_name", "text", microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidTableBase)
            {
                IsNullable = true
            };
            microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidTableBase.Columns.Add("provider_display_name", provider_display_nameColumnBase);
            var provider_keyColumnBase = new ColumnBase<ColumnMappingBase>("provider_key", "text", microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidTableBase);
            microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidTableBase.Columns.Add("provider_key", provider_keyColumnBase);
            var user_idColumnBase0 = new ColumnBase<ColumnMappingBase>("user_id", "uuid", microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidTableBase);
            microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidTableBase.Columns.Add("user_id", user_idColumnBase0);
            relationalModel.DefaultTables.Add("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidTableBase);
            var microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidMappingBase = new TableMappingBase<ColumnMappingBase>(identityUserLogin, microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidTableBase, true);
            microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidTableBase.AddTypeMapping(microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidMappingBase, false);
            defaultTableMappings2.Add(microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)login_providerColumnBase, identityUserLogin.FindProperty("LoginProvider")!, microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)provider_keyColumnBase, identityUserLogin.FindProperty("ProviderKey")!, microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)provider_display_nameColumnBase, identityUserLogin.FindProperty("ProviderDisplayName")!, microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)user_idColumnBase0, identityUserLogin.FindProperty("UserId")!, microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidMappingBase);

            var tableMappings2 = new List<TableMapping>();
            identityUserLogin.SetRuntimeAnnotation("Relational:TableMappings", tableMappings2);
            var aspNetUserLoginsTable = new Table("AspNetUserLogins", null, relationalModel);
            var login_providerColumn = new Column("login_provider", "text", aspNetUserLoginsTable);
            aspNetUserLoginsTable.Columns.Add("login_provider", login_providerColumn);
            var provider_keyColumn = new Column("provider_key", "text", aspNetUserLoginsTable);
            aspNetUserLoginsTable.Columns.Add("provider_key", provider_keyColumn);
            var provider_display_nameColumn = new Column("provider_display_name", "text", aspNetUserLoginsTable)
            {
                IsNullable = true
            };
            aspNetUserLoginsTable.Columns.Add("provider_display_name", provider_display_nameColumn);
            var user_idColumn0 = new Column("user_id", "uuid", aspNetUserLoginsTable);
            aspNetUserLoginsTable.Columns.Add("user_id", user_idColumn0);
            var pk_asp_net_user_logins = new UniqueConstraint("pk_asp_net_user_logins", aspNetUserLoginsTable, new[] { login_providerColumn, provider_keyColumn });
            aspNetUserLoginsTable.PrimaryKey = pk_asp_net_user_logins;
            var pk_asp_net_user_loginsUc = RelationalModel.GetKey(this,
                "Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>",
                new[] { "LoginProvider", "ProviderKey" });
            pk_asp_net_user_logins.MappedKeys.Add(pk_asp_net_user_loginsUc);
            RelationalModel.GetOrCreateUniqueConstraints(pk_asp_net_user_loginsUc).Add(pk_asp_net_user_logins);
            aspNetUserLoginsTable.UniqueConstraints.Add("pk_asp_net_user_logins", pk_asp_net_user_logins);
            var ix_asp_net_user_logins_user_id = new TableIndex(
            "ix_asp_net_user_logins_user_id", aspNetUserLoginsTable, new[] { user_idColumn0 }, false);
            var ix_asp_net_user_logins_user_idIx = RelationalModel.GetIndex(this,
                "Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>",
                new[] { "UserId" });
            ix_asp_net_user_logins_user_id.MappedIndexes.Add(ix_asp_net_user_logins_user_idIx);
            RelationalModel.GetOrCreateTableIndexes(ix_asp_net_user_logins_user_idIx).Add(ix_asp_net_user_logins_user_id);
            aspNetUserLoginsTable.Indexes.Add("ix_asp_net_user_logins_user_id", ix_asp_net_user_logins_user_id);
            relationalModel.Tables.Add(("AspNetUserLogins", null), aspNetUserLoginsTable);
            var aspNetUserLoginsTableMapping = new TableMapping(identityUserLogin, aspNetUserLoginsTable, true);
            aspNetUserLoginsTable.AddTypeMapping(aspNetUserLoginsTableMapping, false);
            tableMappings2.Add(aspNetUserLoginsTableMapping);
            RelationalModel.CreateColumnMapping(login_providerColumn, identityUserLogin.FindProperty("LoginProvider")!, aspNetUserLoginsTableMapping);
            RelationalModel.CreateColumnMapping(provider_keyColumn, identityUserLogin.FindProperty("ProviderKey")!, aspNetUserLoginsTableMapping);
            RelationalModel.CreateColumnMapping(provider_display_nameColumn, identityUserLogin.FindProperty("ProviderDisplayName")!, aspNetUserLoginsTableMapping);
            RelationalModel.CreateColumnMapping(user_idColumn0, identityUserLogin.FindProperty("UserId")!, aspNetUserLoginsTableMapping);

            var identityUserRole = FindEntityType("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>")!;

            var defaultTableMappings3 = new List<TableMappingBase<ColumnMappingBase>>();
            identityUserRole.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings3);
            var microsoftAspNetCoreIdentityIdentityUserRoleSystemGuidTableBase = new TableBase("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", null, relationalModel);
            var role_idColumnBase0 = new ColumnBase<ColumnMappingBase>("role_id", "uuid", microsoftAspNetCoreIdentityIdentityUserRoleSystemGuidTableBase);
            microsoftAspNetCoreIdentityIdentityUserRoleSystemGuidTableBase.Columns.Add("role_id", role_idColumnBase0);
            var user_idColumnBase1 = new ColumnBase<ColumnMappingBase>("user_id", "uuid", microsoftAspNetCoreIdentityIdentityUserRoleSystemGuidTableBase);
            microsoftAspNetCoreIdentityIdentityUserRoleSystemGuidTableBase.Columns.Add("user_id", user_idColumnBase1);
            relationalModel.DefaultTables.Add("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", microsoftAspNetCoreIdentityIdentityUserRoleSystemGuidTableBase);
            var microsoftAspNetCoreIdentityIdentityUserRoleSystemGuidMappingBase = new TableMappingBase<ColumnMappingBase>(identityUserRole, microsoftAspNetCoreIdentityIdentityUserRoleSystemGuidTableBase, true);
            microsoftAspNetCoreIdentityIdentityUserRoleSystemGuidTableBase.AddTypeMapping(microsoftAspNetCoreIdentityIdentityUserRoleSystemGuidMappingBase, false);
            defaultTableMappings3.Add(microsoftAspNetCoreIdentityIdentityUserRoleSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)role_idColumnBase0, identityUserRole.FindProperty("RoleId")!, microsoftAspNetCoreIdentityIdentityUserRoleSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)user_idColumnBase1, identityUserRole.FindProperty("UserId")!, microsoftAspNetCoreIdentityIdentityUserRoleSystemGuidMappingBase);

            var tableMappings3 = new List<TableMapping>();
            identityUserRole.SetRuntimeAnnotation("Relational:TableMappings", tableMappings3);
            var aspNetUserRolesTable = new Table("AspNetUserRoles", null, relationalModel);
            var user_idColumn1 = new Column("user_id", "uuid", aspNetUserRolesTable);
            aspNetUserRolesTable.Columns.Add("user_id", user_idColumn1);
            var role_idColumn0 = new Column("role_id", "uuid", aspNetUserRolesTable);
            aspNetUserRolesTable.Columns.Add("role_id", role_idColumn0);
            var pk_asp_net_user_roles = new UniqueConstraint("pk_asp_net_user_roles", aspNetUserRolesTable, new[] { user_idColumn1, role_idColumn0 });
            aspNetUserRolesTable.PrimaryKey = pk_asp_net_user_roles;
            var pk_asp_net_user_rolesUc = RelationalModel.GetKey(this,
                "Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>",
                new[] { "UserId", "RoleId" });
            pk_asp_net_user_roles.MappedKeys.Add(pk_asp_net_user_rolesUc);
            RelationalModel.GetOrCreateUniqueConstraints(pk_asp_net_user_rolesUc).Add(pk_asp_net_user_roles);
            aspNetUserRolesTable.UniqueConstraints.Add("pk_asp_net_user_roles", pk_asp_net_user_roles);
            var ix_asp_net_user_roles_role_id = new TableIndex(
            "ix_asp_net_user_roles_role_id", aspNetUserRolesTable, new[] { role_idColumn0 }, false);
            var ix_asp_net_user_roles_role_idIx = RelationalModel.GetIndex(this,
                "Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>",
                new[] { "RoleId" });
            ix_asp_net_user_roles_role_id.MappedIndexes.Add(ix_asp_net_user_roles_role_idIx);
            RelationalModel.GetOrCreateTableIndexes(ix_asp_net_user_roles_role_idIx).Add(ix_asp_net_user_roles_role_id);
            aspNetUserRolesTable.Indexes.Add("ix_asp_net_user_roles_role_id", ix_asp_net_user_roles_role_id);
            relationalModel.Tables.Add(("AspNetUserRoles", null), aspNetUserRolesTable);
            var aspNetUserRolesTableMapping = new TableMapping(identityUserRole, aspNetUserRolesTable, true);
            aspNetUserRolesTable.AddTypeMapping(aspNetUserRolesTableMapping, false);
            tableMappings3.Add(aspNetUserRolesTableMapping);
            RelationalModel.CreateColumnMapping(role_idColumn0, identityUserRole.FindProperty("RoleId")!, aspNetUserRolesTableMapping);
            RelationalModel.CreateColumnMapping(user_idColumn1, identityUserRole.FindProperty("UserId")!, aspNetUserRolesTableMapping);

            var identityUserToken = FindEntityType("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>")!;

            var defaultTableMappings4 = new List<TableMappingBase<ColumnMappingBase>>();
            identityUserToken.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings4);
            var microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidTableBase = new TableBase("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", null, relationalModel);
            var login_providerColumnBase0 = new ColumnBase<ColumnMappingBase>("login_provider", "text", microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidTableBase);
            microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidTableBase.Columns.Add("login_provider", login_providerColumnBase0);
            var nameColumnBase0 = new ColumnBase<ColumnMappingBase>("name", "text", microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidTableBase);
            microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidTableBase.Columns.Add("name", nameColumnBase0);
            var user_idColumnBase2 = new ColumnBase<ColumnMappingBase>("user_id", "uuid", microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidTableBase);
            microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidTableBase.Columns.Add("user_id", user_idColumnBase2);
            var valueColumnBase = new ColumnBase<ColumnMappingBase>("value", "text", microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidTableBase)
            {
                IsNullable = true
            };
            microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidTableBase.Columns.Add("value", valueColumnBase);
            relationalModel.DefaultTables.Add("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidTableBase);
            var microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidMappingBase = new TableMappingBase<ColumnMappingBase>(identityUserToken, microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidTableBase, true);
            microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidTableBase.AddTypeMapping(microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidMappingBase, false);
            defaultTableMappings4.Add(microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)login_providerColumnBase0, identityUserToken.FindProperty("LoginProvider")!, microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase0, identityUserToken.FindProperty("Name")!, microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)user_idColumnBase2, identityUserToken.FindProperty("UserId")!, microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)valueColumnBase, identityUserToken.FindProperty("Value")!, microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidMappingBase);

            var tableMappings4 = new List<TableMapping>();
            identityUserToken.SetRuntimeAnnotation("Relational:TableMappings", tableMappings4);
            var aspNetUserTokensTable = new Table("AspNetUserTokens", null, relationalModel);
            var user_idColumn2 = new Column("user_id", "uuid", aspNetUserTokensTable);
            aspNetUserTokensTable.Columns.Add("user_id", user_idColumn2);
            var login_providerColumn0 = new Column("login_provider", "text", aspNetUserTokensTable);
            aspNetUserTokensTable.Columns.Add("login_provider", login_providerColumn0);
            var nameColumn0 = new Column("name", "text", aspNetUserTokensTable);
            aspNetUserTokensTable.Columns.Add("name", nameColumn0);
            var valueColumn = new Column("value", "text", aspNetUserTokensTable)
            {
                IsNullable = true
            };
            aspNetUserTokensTable.Columns.Add("value", valueColumn);
            var pk_asp_net_user_tokens = new UniqueConstraint("pk_asp_net_user_tokens", aspNetUserTokensTable, new[] { user_idColumn2, login_providerColumn0, nameColumn0 });
            aspNetUserTokensTable.PrimaryKey = pk_asp_net_user_tokens;
            var pk_asp_net_user_tokensUc = RelationalModel.GetKey(this,
                "Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>",
                new[] { "UserId", "LoginProvider", "Name" });
            pk_asp_net_user_tokens.MappedKeys.Add(pk_asp_net_user_tokensUc);
            RelationalModel.GetOrCreateUniqueConstraints(pk_asp_net_user_tokensUc).Add(pk_asp_net_user_tokens);
            aspNetUserTokensTable.UniqueConstraints.Add("pk_asp_net_user_tokens", pk_asp_net_user_tokens);
            relationalModel.Tables.Add(("AspNetUserTokens", null), aspNetUserTokensTable);
            var aspNetUserTokensTableMapping = new TableMapping(identityUserToken, aspNetUserTokensTable, true);
            aspNetUserTokensTable.AddTypeMapping(aspNetUserTokensTableMapping, false);
            tableMappings4.Add(aspNetUserTokensTableMapping);
            RelationalModel.CreateColumnMapping(login_providerColumn0, identityUserToken.FindProperty("LoginProvider")!, aspNetUserTokensTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn0, identityUserToken.FindProperty("Name")!, aspNetUserTokensTableMapping);
            RelationalModel.CreateColumnMapping(user_idColumn2, identityUserToken.FindProperty("UserId")!, aspNetUserTokensTableMapping);
            RelationalModel.CreateColumnMapping(valueColumn, identityUserToken.FindProperty("Value")!, aspNetUserTokensTableMapping);

            var address = FindEntityType("Modulith.Modules.Users.Contracts.Address")!;

            var defaultTableMappings5 = new List<TableMappingBase<ColumnMappingBase>>();
            address.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings5);
            var modulithModulesUsersContractsAddressTableBase = new TableBase("Modulith.Modules.Users.Contracts.Address", null, relationalModel);
            var addressColumnBase = new JsonColumnBase("address", "jsonb", modulithModulesUsersContractsAddressTableBase)
            {
                IsNullable = true
            };
            modulithModulesUsersContractsAddressTableBase.Columns.Add("address", addressColumnBase);
            relationalModel.DefaultTables.Add("Modulith.Modules.Users.Contracts.Address", modulithModulesUsersContractsAddressTableBase);
            var modulithModulesUsersContractsAddressMappingBase = new TableMappingBase<ColumnMappingBase>(address, modulithModulesUsersContractsAddressTableBase, true);
            modulithModulesUsersContractsAddressTableBase.AddTypeMapping(modulithModulesUsersContractsAddressMappingBase, false);
            defaultTableMappings5.Add(modulithModulesUsersContractsAddressMappingBase);

            var tableMappings5 = new List<TableMapping>();
            address.SetRuntimeAnnotation("Relational:TableMappings", tableMappings5);
            var aspNetUsersTable = new Table("AspNetUsers", null, relationalModel);
            var idColumn2 = new Column("id", "uuid", aspNetUsersTable);
            aspNetUsersTable.Columns.Add("id", idColumn2);
            var access_failed_countColumn = new Column("access_failed_count", "integer", aspNetUsersTable);
            aspNetUsersTable.Columns.Add("access_failed_count", access_failed_countColumn);
            var addressColumn = new JsonColumn("address", "jsonb", aspNetUsersTable)
            {
                IsNullable = true
            };
            aspNetUsersTable.Columns.Add("address", addressColumn);
            var concurrency_stampColumn0 = new Column("concurrency_stamp", "text", aspNetUsersTable)
            {
                IsNullable = true
            };
            aspNetUsersTable.Columns.Add("concurrency_stamp", concurrency_stampColumn0);
            var emailColumn = new Column("email", "character varying(256)", aspNetUsersTable)
            {
                IsNullable = true
            };
            aspNetUsersTable.Columns.Add("email", emailColumn);
            var email_confirmedColumn = new Column("email_confirmed", "boolean", aspNetUsersTable);
            aspNetUsersTable.Columns.Add("email_confirmed", email_confirmedColumn);
            var full_nameColumn = new Column("full_name", "character varying(50)", aspNetUsersTable);
            aspNetUsersTable.Columns.Add("full_name", full_nameColumn);
            var lockout_enabledColumn = new Column("lockout_enabled", "boolean", aspNetUsersTable);
            aspNetUsersTable.Columns.Add("lockout_enabled", lockout_enabledColumn);
            var lockout_endColumn = new Column("lockout_end", "timestamp with time zone", aspNetUsersTable)
            {
                IsNullable = true
            };
            aspNetUsersTable.Columns.Add("lockout_end", lockout_endColumn);
            var normalized_emailColumn = new Column("normalized_email", "character varying(256)", aspNetUsersTable)
            {
                IsNullable = true
            };
            aspNetUsersTable.Columns.Add("normalized_email", normalized_emailColumn);
            var normalized_user_nameColumn = new Column("normalized_user_name", "character varying(256)", aspNetUsersTable)
            {
                IsNullable = true
            };
            aspNetUsersTable.Columns.Add("normalized_user_name", normalized_user_nameColumn);
            var password_hashColumn = new Column("password_hash", "text", aspNetUsersTable)
            {
                IsNullable = true
            };
            aspNetUsersTable.Columns.Add("password_hash", password_hashColumn);
            var phone_numberColumn = new Column("phone_number", "character varying(10)", aspNetUsersTable)
            {
                IsNullable = true
            };
            aspNetUsersTable.Columns.Add("phone_number", phone_numberColumn);
            var phone_number_confirmedColumn = new Column("phone_number_confirmed", "boolean", aspNetUsersTable);
            aspNetUsersTable.Columns.Add("phone_number_confirmed", phone_number_confirmedColumn);
            var security_stampColumn = new Column("security_stamp", "text", aspNetUsersTable)
            {
                IsNullable = true
            };
            aspNetUsersTable.Columns.Add("security_stamp", security_stampColumn);
            var two_factor_enabledColumn = new Column("two_factor_enabled", "boolean", aspNetUsersTable);
            aspNetUsersTable.Columns.Add("two_factor_enabled", two_factor_enabledColumn);
            var user_nameColumn = new Column("user_name", "character varying(256)", aspNetUsersTable)
            {
                IsNullable = true
            };
            aspNetUsersTable.Columns.Add("user_name", user_nameColumn);
            var pk_asp_net_users = new UniqueConstraint("pk_asp_net_users", aspNetUsersTable, new[] { idColumn2 });
            aspNetUsersTable.PrimaryKey = pk_asp_net_users;
            var pk_asp_net_usersUc = RelationalModel.GetKey(this,
                "Modulith.Modules.Users.Domain.ApplicationUser",
                new[] { "Id" });
            pk_asp_net_users.MappedKeys.Add(pk_asp_net_usersUc);
            RelationalModel.GetOrCreateUniqueConstraints(pk_asp_net_usersUc).Add(pk_asp_net_users);
            aspNetUsersTable.UniqueConstraints.Add("pk_asp_net_users", pk_asp_net_users);
            var emailIndex = new TableIndex(
            "EmailIndex", aspNetUsersTable, new[] { normalized_emailColumn }, false);
            var emailIndexIx = RelationalModel.GetIndex(this,
                "Modulith.Modules.Users.Domain.ApplicationUser",
                new[] { "NormalizedEmail" });
            emailIndex.MappedIndexes.Add(emailIndexIx);
            RelationalModel.GetOrCreateTableIndexes(emailIndexIx).Add(emailIndex);
            aspNetUsersTable.Indexes.Add("EmailIndex", emailIndex);
            var userNameIndex = new TableIndex(
            "UserNameIndex", aspNetUsersTable, new[] { normalized_user_nameColumn }, true);
            var userNameIndexIx = RelationalModel.GetIndex(this,
                "Modulith.Modules.Users.Domain.ApplicationUser",
                new[] { "NormalizedUserName" });
            userNameIndex.MappedIndexes.Add(userNameIndexIx);
            RelationalModel.GetOrCreateTableIndexes(userNameIndexIx).Add(userNameIndex);
            aspNetUsersTable.Indexes.Add("UserNameIndex", userNameIndex);
            relationalModel.Tables.Add(("AspNetUsers", null), aspNetUsersTable);
            var aspNetUsersTableMapping = new TableMapping(address, aspNetUsersTable, true)
            {
                IsSharedTablePrincipal = false,
            };
            aspNetUsersTable.AddTypeMapping(aspNetUsersTableMapping, true);
            tableMappings5.Add(aspNetUsersTableMapping);
            aspNetUsersTable.AddRowInternalForeignKey(address, RelationalModel.GetForeignKey(this,
                "Modulith.Modules.Users.Contracts.Address",
                new[] { "ApplicationUserId" },
                "Modulith.Modules.Users.Domain.ApplicationUser",
                new[] { "Id" }));

            var applicationUser = FindEntityType("Modulith.Modules.Users.Domain.ApplicationUser")!;

            var defaultTableMappings6 = new List<TableMappingBase<ColumnMappingBase>>();
            applicationUser.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings6);
            var modulithModulesUsersDomainApplicationUserTableBase = new TableBase("Modulith.Modules.Users.Domain.ApplicationUser", null, relationalModel);
            var access_failed_countColumnBase = new ColumnBase<ColumnMappingBase>("access_failed_count", "integer", modulithModulesUsersDomainApplicationUserTableBase);
            modulithModulesUsersDomainApplicationUserTableBase.Columns.Add("access_failed_count", access_failed_countColumnBase);
            var concurrency_stampColumnBase0 = new ColumnBase<ColumnMappingBase>("concurrency_stamp", "text", modulithModulesUsersDomainApplicationUserTableBase)
            {
                IsNullable = true
            };
            modulithModulesUsersDomainApplicationUserTableBase.Columns.Add("concurrency_stamp", concurrency_stampColumnBase0);
            var emailColumnBase = new ColumnBase<ColumnMappingBase>("email", "character varying(256)", modulithModulesUsersDomainApplicationUserTableBase)
            {
                IsNullable = true
            };
            modulithModulesUsersDomainApplicationUserTableBase.Columns.Add("email", emailColumnBase);
            var email_confirmedColumnBase = new ColumnBase<ColumnMappingBase>("email_confirmed", "boolean", modulithModulesUsersDomainApplicationUserTableBase);
            modulithModulesUsersDomainApplicationUserTableBase.Columns.Add("email_confirmed", email_confirmedColumnBase);
            var full_nameColumnBase = new ColumnBase<ColumnMappingBase>("full_name", "character varying(50)", modulithModulesUsersDomainApplicationUserTableBase);
            modulithModulesUsersDomainApplicationUserTableBase.Columns.Add("full_name", full_nameColumnBase);
            var idColumnBase2 = new ColumnBase<ColumnMappingBase>("id", "uuid", modulithModulesUsersDomainApplicationUserTableBase);
            modulithModulesUsersDomainApplicationUserTableBase.Columns.Add("id", idColumnBase2);
            var lockout_enabledColumnBase = new ColumnBase<ColumnMappingBase>("lockout_enabled", "boolean", modulithModulesUsersDomainApplicationUserTableBase);
            modulithModulesUsersDomainApplicationUserTableBase.Columns.Add("lockout_enabled", lockout_enabledColumnBase);
            var lockout_endColumnBase = new ColumnBase<ColumnMappingBase>("lockout_end", "timestamp with time zone", modulithModulesUsersDomainApplicationUserTableBase)
            {
                IsNullable = true
            };
            modulithModulesUsersDomainApplicationUserTableBase.Columns.Add("lockout_end", lockout_endColumnBase);
            var normalized_emailColumnBase = new ColumnBase<ColumnMappingBase>("normalized_email", "character varying(256)", modulithModulesUsersDomainApplicationUserTableBase)
            {
                IsNullable = true
            };
            modulithModulesUsersDomainApplicationUserTableBase.Columns.Add("normalized_email", normalized_emailColumnBase);
            var normalized_user_nameColumnBase = new ColumnBase<ColumnMappingBase>("normalized_user_name", "character varying(256)", modulithModulesUsersDomainApplicationUserTableBase)
            {
                IsNullable = true
            };
            modulithModulesUsersDomainApplicationUserTableBase.Columns.Add("normalized_user_name", normalized_user_nameColumnBase);
            var password_hashColumnBase = new ColumnBase<ColumnMappingBase>("password_hash", "text", modulithModulesUsersDomainApplicationUserTableBase)
            {
                IsNullable = true
            };
            modulithModulesUsersDomainApplicationUserTableBase.Columns.Add("password_hash", password_hashColumnBase);
            var phone_numberColumnBase = new ColumnBase<ColumnMappingBase>("phone_number", "character varying(10)", modulithModulesUsersDomainApplicationUserTableBase)
            {
                IsNullable = true
            };
            modulithModulesUsersDomainApplicationUserTableBase.Columns.Add("phone_number", phone_numberColumnBase);
            var phone_number_confirmedColumnBase = new ColumnBase<ColumnMappingBase>("phone_number_confirmed", "boolean", modulithModulesUsersDomainApplicationUserTableBase);
            modulithModulesUsersDomainApplicationUserTableBase.Columns.Add("phone_number_confirmed", phone_number_confirmedColumnBase);
            var security_stampColumnBase = new ColumnBase<ColumnMappingBase>("security_stamp", "text", modulithModulesUsersDomainApplicationUserTableBase)
            {
                IsNullable = true
            };
            modulithModulesUsersDomainApplicationUserTableBase.Columns.Add("security_stamp", security_stampColumnBase);
            var two_factor_enabledColumnBase = new ColumnBase<ColumnMappingBase>("two_factor_enabled", "boolean", modulithModulesUsersDomainApplicationUserTableBase);
            modulithModulesUsersDomainApplicationUserTableBase.Columns.Add("two_factor_enabled", two_factor_enabledColumnBase);
            var user_nameColumnBase = new ColumnBase<ColumnMappingBase>("user_name", "character varying(256)", modulithModulesUsersDomainApplicationUserTableBase)
            {
                IsNullable = true
            };
            modulithModulesUsersDomainApplicationUserTableBase.Columns.Add("user_name", user_nameColumnBase);
            relationalModel.DefaultTables.Add("Modulith.Modules.Users.Domain.ApplicationUser", modulithModulesUsersDomainApplicationUserTableBase);
            var modulithModulesUsersDomainApplicationUserMappingBase = new TableMappingBase<ColumnMappingBase>(applicationUser, modulithModulesUsersDomainApplicationUserTableBase, true);
            modulithModulesUsersDomainApplicationUserTableBase.AddTypeMapping(modulithModulesUsersDomainApplicationUserMappingBase, false);
            defaultTableMappings6.Add(modulithModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase2, applicationUser.FindProperty("Id")!, modulithModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)access_failed_countColumnBase, applicationUser.FindProperty("AccessFailedCount")!, modulithModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)concurrency_stampColumnBase0, applicationUser.FindProperty("ConcurrencyStamp")!, modulithModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)emailColumnBase, applicationUser.FindProperty("Email")!, modulithModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)email_confirmedColumnBase, applicationUser.FindProperty("EmailConfirmed")!, modulithModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)full_nameColumnBase, applicationUser.FindProperty("FullName")!, modulithModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)lockout_enabledColumnBase, applicationUser.FindProperty("LockoutEnabled")!, modulithModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)lockout_endColumnBase, applicationUser.FindProperty("LockoutEnd")!, modulithModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)normalized_emailColumnBase, applicationUser.FindProperty("NormalizedEmail")!, modulithModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)normalized_user_nameColumnBase, applicationUser.FindProperty("NormalizedUserName")!, modulithModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)password_hashColumnBase, applicationUser.FindProperty("PasswordHash")!, modulithModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)phone_numberColumnBase, applicationUser.FindProperty("PhoneNumber")!, modulithModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)phone_number_confirmedColumnBase, applicationUser.FindProperty("PhoneNumberConfirmed")!, modulithModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)security_stampColumnBase, applicationUser.FindProperty("SecurityStamp")!, modulithModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)two_factor_enabledColumnBase, applicationUser.FindProperty("TwoFactorEnabled")!, modulithModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)user_nameColumnBase, applicationUser.FindProperty("UserName")!, modulithModulesUsersDomainApplicationUserMappingBase);

            var tableMappings6 = new List<TableMapping>();
            applicationUser.SetRuntimeAnnotation("Relational:TableMappings", tableMappings6);
            var aspNetUsersTableMapping0 = new TableMapping(applicationUser, aspNetUsersTable, true)
            {
                IsSharedTablePrincipal = true,
            };
            aspNetUsersTable.AddTypeMapping(aspNetUsersTableMapping0, false);
            tableMappings6.Add(aspNetUsersTableMapping0);
            RelationalModel.CreateColumnMapping(idColumn2, applicationUser.FindProperty("Id")!, aspNetUsersTableMapping0);
            RelationalModel.CreateColumnMapping(access_failed_countColumn, applicationUser.FindProperty("AccessFailedCount")!, aspNetUsersTableMapping0);
            RelationalModel.CreateColumnMapping(concurrency_stampColumn0, applicationUser.FindProperty("ConcurrencyStamp")!, aspNetUsersTableMapping0);
            RelationalModel.CreateColumnMapping(emailColumn, applicationUser.FindProperty("Email")!, aspNetUsersTableMapping0);
            RelationalModel.CreateColumnMapping(email_confirmedColumn, applicationUser.FindProperty("EmailConfirmed")!, aspNetUsersTableMapping0);
            RelationalModel.CreateColumnMapping(full_nameColumn, applicationUser.FindProperty("FullName")!, aspNetUsersTableMapping0);
            RelationalModel.CreateColumnMapping(lockout_enabledColumn, applicationUser.FindProperty("LockoutEnabled")!, aspNetUsersTableMapping0);
            RelationalModel.CreateColumnMapping(lockout_endColumn, applicationUser.FindProperty("LockoutEnd")!, aspNetUsersTableMapping0);
            RelationalModel.CreateColumnMapping(normalized_emailColumn, applicationUser.FindProperty("NormalizedEmail")!, aspNetUsersTableMapping0);
            RelationalModel.CreateColumnMapping(normalized_user_nameColumn, applicationUser.FindProperty("NormalizedUserName")!, aspNetUsersTableMapping0);
            RelationalModel.CreateColumnMapping(password_hashColumn, applicationUser.FindProperty("PasswordHash")!, aspNetUsersTableMapping0);
            RelationalModel.CreateColumnMapping(phone_numberColumn, applicationUser.FindProperty("PhoneNumber")!, aspNetUsersTableMapping0);
            RelationalModel.CreateColumnMapping(phone_number_confirmedColumn, applicationUser.FindProperty("PhoneNumberConfirmed")!, aspNetUsersTableMapping0);
            RelationalModel.CreateColumnMapping(security_stampColumn, applicationUser.FindProperty("SecurityStamp")!, aspNetUsersTableMapping0);
            RelationalModel.CreateColumnMapping(two_factor_enabledColumn, applicationUser.FindProperty("TwoFactorEnabled")!, aspNetUsersTableMapping0);
            RelationalModel.CreateColumnMapping(user_nameColumn, applicationUser.FindProperty("UserName")!, aspNetUsersTableMapping0);
            var fk_asp_net_role_claims_asp_net_roles_role_id = new ForeignKeyConstraint(
                "fk_asp_net_role_claims_asp_net_roles_role_id", aspNetRoleClaimsTable, aspNetRolesTable,
                new[] { role_idColumn },
                aspNetRolesTable.FindUniqueConstraint("pk_asp_net_roles")!, ReferentialAction.Cascade);
            var fk_asp_net_role_claims_asp_net_roles_role_idFk = RelationalModel.GetForeignKey(this,
                "Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>",
                new[] { "RoleId" },
                "Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>",
                new[] { "Id" });
            fk_asp_net_role_claims_asp_net_roles_role_id.MappedForeignKeys.Add(fk_asp_net_role_claims_asp_net_roles_role_idFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fk_asp_net_role_claims_asp_net_roles_role_idFk).Add(fk_asp_net_role_claims_asp_net_roles_role_id);
            aspNetRoleClaimsTable.ForeignKeyConstraints.Add(fk_asp_net_role_claims_asp_net_roles_role_id);
            aspNetRolesTable.ReferencingForeignKeyConstraints.Add(fk_asp_net_role_claims_asp_net_roles_role_id);
            var fk_asp_net_user_claims_asp_net_users_user_id = new ForeignKeyConstraint(
                "fk_asp_net_user_claims_asp_net_users_user_id", aspNetUserClaimsTable, aspNetUsersTable,
                new[] { user_idColumn },
                aspNetUsersTable.FindUniqueConstraint("pk_asp_net_users")!, ReferentialAction.Cascade);
            var fk_asp_net_user_claims_asp_net_users_user_idFk = RelationalModel.GetForeignKey(this,
                "Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>",
                new[] { "UserId" },
                "Modulith.Modules.Users.Domain.ApplicationUser",
                new[] { "Id" });
            fk_asp_net_user_claims_asp_net_users_user_id.MappedForeignKeys.Add(fk_asp_net_user_claims_asp_net_users_user_idFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fk_asp_net_user_claims_asp_net_users_user_idFk).Add(fk_asp_net_user_claims_asp_net_users_user_id);
            aspNetUserClaimsTable.ForeignKeyConstraints.Add(fk_asp_net_user_claims_asp_net_users_user_id);
            aspNetUsersTable.ReferencingForeignKeyConstraints.Add(fk_asp_net_user_claims_asp_net_users_user_id);
            var fk_asp_net_user_logins_asp_net_users_user_id = new ForeignKeyConstraint(
                "fk_asp_net_user_logins_asp_net_users_user_id", aspNetUserLoginsTable, aspNetUsersTable,
                new[] { user_idColumn0 },
                aspNetUsersTable.FindUniqueConstraint("pk_asp_net_users")!, ReferentialAction.Cascade);
            var fk_asp_net_user_logins_asp_net_users_user_idFk = RelationalModel.GetForeignKey(this,
                "Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>",
                new[] { "UserId" },
                "Modulith.Modules.Users.Domain.ApplicationUser",
                new[] { "Id" });
            fk_asp_net_user_logins_asp_net_users_user_id.MappedForeignKeys.Add(fk_asp_net_user_logins_asp_net_users_user_idFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fk_asp_net_user_logins_asp_net_users_user_idFk).Add(fk_asp_net_user_logins_asp_net_users_user_id);
            aspNetUserLoginsTable.ForeignKeyConstraints.Add(fk_asp_net_user_logins_asp_net_users_user_id);
            aspNetUsersTable.ReferencingForeignKeyConstraints.Add(fk_asp_net_user_logins_asp_net_users_user_id);
            var fk_asp_net_user_roles_asp_net_roles_role_id = new ForeignKeyConstraint(
                "fk_asp_net_user_roles_asp_net_roles_role_id", aspNetUserRolesTable, aspNetRolesTable,
                new[] { role_idColumn0 },
                aspNetRolesTable.FindUniqueConstraint("pk_asp_net_roles")!, ReferentialAction.Cascade);
            var fk_asp_net_user_roles_asp_net_roles_role_idFk = RelationalModel.GetForeignKey(this,
                "Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>",
                new[] { "RoleId" },
                "Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>",
                new[] { "Id" });
            fk_asp_net_user_roles_asp_net_roles_role_id.MappedForeignKeys.Add(fk_asp_net_user_roles_asp_net_roles_role_idFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fk_asp_net_user_roles_asp_net_roles_role_idFk).Add(fk_asp_net_user_roles_asp_net_roles_role_id);
            aspNetUserRolesTable.ForeignKeyConstraints.Add(fk_asp_net_user_roles_asp_net_roles_role_id);
            aspNetRolesTable.ReferencingForeignKeyConstraints.Add(fk_asp_net_user_roles_asp_net_roles_role_id);
            var fk_asp_net_user_roles_asp_net_users_user_id = new ForeignKeyConstraint(
                "fk_asp_net_user_roles_asp_net_users_user_id", aspNetUserRolesTable, aspNetUsersTable,
                new[] { user_idColumn1 },
                aspNetUsersTable.FindUniqueConstraint("pk_asp_net_users")!, ReferentialAction.Cascade);
            var fk_asp_net_user_roles_asp_net_users_user_idFk = RelationalModel.GetForeignKey(this,
                "Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>",
                new[] { "UserId" },
                "Modulith.Modules.Users.Domain.ApplicationUser",
                new[] { "Id" });
            fk_asp_net_user_roles_asp_net_users_user_id.MappedForeignKeys.Add(fk_asp_net_user_roles_asp_net_users_user_idFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fk_asp_net_user_roles_asp_net_users_user_idFk).Add(fk_asp_net_user_roles_asp_net_users_user_id);
            aspNetUserRolesTable.ForeignKeyConstraints.Add(fk_asp_net_user_roles_asp_net_users_user_id);
            aspNetUsersTable.ReferencingForeignKeyConstraints.Add(fk_asp_net_user_roles_asp_net_users_user_id);
            var fk_asp_net_user_tokens_asp_net_users_user_id = new ForeignKeyConstraint(
                "fk_asp_net_user_tokens_asp_net_users_user_id", aspNetUserTokensTable, aspNetUsersTable,
                new[] { user_idColumn2 },
                aspNetUsersTable.FindUniqueConstraint("pk_asp_net_users")!, ReferentialAction.Cascade);
            var fk_asp_net_user_tokens_asp_net_users_user_idFk = RelationalModel.GetForeignKey(this,
                "Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>",
                new[] { "UserId" },
                "Modulith.Modules.Users.Domain.ApplicationUser",
                new[] { "Id" });
            fk_asp_net_user_tokens_asp_net_users_user_id.MappedForeignKeys.Add(fk_asp_net_user_tokens_asp_net_users_user_idFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fk_asp_net_user_tokens_asp_net_users_user_idFk).Add(fk_asp_net_user_tokens_asp_net_users_user_id);
            aspNetUserTokensTable.ForeignKeyConstraints.Add(fk_asp_net_user_tokens_asp_net_users_user_id);
            aspNetUsersTable.ReferencingForeignKeyConstraints.Add(fk_asp_net_user_tokens_asp_net_users_user_id);
            return relationalModel.MakeReadOnly();
        }
    }
}
