version: "3.9"

services:
  db:
    image: postgres:16.2-alpine3.19
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
    command:
      - bash
      - -c
      - docker-entrypoint.sh -c config_file=/etc/postgresql/postgres.conf -c hba_file=/etc/postgresql/pg_hba.conf
    volumes:
      - ./vol/postgres:/data/postgres
      - ./docker/postgresql:/etc/postgresql
    restart: unless-stopped
    networks:
      - modulith-network

  cache:
    image: redis/redis-stack:7.2.0-v10
    container_name: redis-stack
    ports:
      - 6378:6379
    volumes:
      - ./vol/redis:/data
    restart: unless-stopped
    networks:
      - modulith-network

  storage:
    image: mcr.microsoft.com/azure-storage/azurite:3.29.0
    container_name: azurite
    ports:
      - 10000-10002:10000-10002
    command: "azurite-blob --blobHost 0.0.0.0 -l /data --silent"
    restart: always
    volumes:
      - ./vol/azurite:/data
    networks:
      - modulith-network

networks:
  modulith-network:
    driver: bridge
